language: node_js
node_js: node
deploy:
  provider: npm
  email: mail@qwtel.com
  api_key:
    secure: DeoMFI6rC1QVXB5La1WaedOE6n3e85o1UdJ7Jmh2rwKzTUPJoQw6NoetheZO/LSoYEb7bgNj141dWG5JtUIIwnQIvMcjG2eSoJ7Bs5hQ/rGyQuJeiLXRGSXDqRWkgMIIn8NUTYigK6iKgrvrUg6odqHjW1df4EV+vaclpf2fc+pcKb0wAYS2bqPscbPZGREO/BS0Nd25QYqhaCTFiHT8TEaHPzu12mN3smbv7NFI9VyyHPfU8fURkW7NXdsunIesOCXGjXy56ycGBqWcPf5IxG3OGzmImzoXMnwE1cQNOg4ntoPeU8PRWh2yF5jipuSqRqTnghrL2o8jwSofb8i0Vi4Ygpn89Wf6z7qWrDMNhxlSvhoy7bX0/2SMxOJguwzV/bNhe09EsVxj2niNOmMyMKJyZJHCtpucFnw4n94x5NnpiXJvrVgocTZ0t7TOQsfWxsgSMBfEYbi3v7ViZW7eQ9fLZwPhpWfK2h8cjuxDAtdfSOc6hRBM5vrKHZpcJs9oTM6PA2z/ewvOM+exb+Gqaw+FaizLmYCnS4OwOHL1akexvSq5hhXA0HIx2dGXim3IlvSvzEz0RoEewT2qnfx8BPpgzbAoUSg9p0NntK3btImj7EXsO4X3BzZiYl26AKT1V9Ngo3Rt2bJqJEi1fve33REEoRmYiejWEdTUqaotmO0=
  on:
    tags: true
    repo: platformparity/web-cryptography
